server:
  #  tomcat??
  port: 8080
spring:
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password:
    masterslave:
      # 读写分离配置 负载均衡
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主数据源名称
      master-data-source-name: master
      # 从数据源名称
      slave-data-source-names: slave
    props:
      sql:
        # 开启sql显示
        show: true
  main:
    # 允许Bean覆盖
    allow-bean-definition-overriding: true
  cache:
    redis:
      time-to-live: 3600s
  application:
    name: reggie
  redis:
    host: 127.0.0.1
    port: 6379
    # 默认操作0号数据库
    database: 0
    jedis:
      #redis连接池配置
      pool:
        max-active: 8   #最大连接数
        max-wait: 1ms   #最大阻塞时间
        max-idle: 4     #最大空闲连接
        min-idle: 0     #最小空闲连接
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  file:
    uploadPath: E://tempFile//upload//
    downloadPath: E://tempFile//download//